### ISSUE TITLE
pdoc does not work if "." is specified while specifying the directory

### ISSUE THREAD

**Issue by anshuman-goel** [mitmproxy/pdoc#812]
#### Problem Description
When I specify . while running the pdoc command like `python -m pdoc .` it throws an error `ValueError: No modules found matching spec: .` I want to run pdoc from this directory because my `pyproject.toml` resides in there and I want to specify the command for generating the docs in there. I found a turnaround for this by specifying it like `python -m pdoc ..\folder-name`. It works but if my folder name has a `-` in the name it fails with the same error.

#### Steps to reproduce the behavior:
1. Create a project with `pyproject.toml` file.
2. Add the pdoc command using poetry poe extension

```
[tool.poe.tasks.generate-docs-localhost]
cmd = "python -m pdoc .
```

3. Observe the error `ValueError: No modules found matching spec: .`

#### System Information
Paste the output of "pdoc --version" here.
15.0.1

**Comment by mhils** [comment]
What does your directory structure look like? 
Typically your pyproject.toml directory does not have a `__init__.py` and is not a module.

**Comment by anshuman-goel** [comment]
My function directory closely follows [Azure function directory structure](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=get-started%2Casgi%2Capplication-level&pivots=python-mode-decorators#folder-structure). It is like below:

```
<project.root>/
 | - .venv/
 | - .vscode/
 | - function_app.py
 | - additional_functions.py
 | - __init__.py
 | - additional_folder/
 | | - __init__.py
 | | - other_files.py
 | - tests/
 | | - test_my_function.py
 | - .funcignore
 | - host.json
 | - local.settings.json
 | - requirements.txt
 | - pyproject.toml
```

**Comment by mhils** [comment]
`pdoc .` should work now in line with how the rest of pdoc works. :)

**Comment by anshuman-goel** [comment]
Hi @mhils, it looks like the issue still persists.

There appears to be a problem in [walk_specs](https://github.com/mhils/pdoc/blob/75863d3abac0843a4ca0f3d562db2bc21d6ba6dc/pdoc/extract.py#L110). Additionally, the current PR doesn’t seem to account for cases where the folder name contains a `.`, which might be causing unexpected behavior.

For reference, I’m testing this on Windows with version 15.0.4.

**Comment by mhils** [comment]
> There appears to be a problem in [walk_specs](https://github.com/mhils/pdoc/blob/75863d3abac0843a4ca0f3d562db2bc21d6ba6dc/pdoc/extract.py#L110). Additionally, the current PR test case doesn’t seem to account for cases where the folder name contains a `.`.

By putting a `__init__.py` file in your root directory, you declare it to be a module. Module names in Python are lowercase ASCII + underscores. Don't put dots in your module name.
